name: ci

on:
  push:
    branches:
      - "main"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Building Docker Image and Pushing to Dockerhub
        uses: docker/build-push-action@v3
        with:
          file: ./dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/bitebot-chatapi:latest